---
- name: Pull and Run docker image of pparth27743/hello_world
  hosts: all
  tasks:
    - name: Pull pparth27743/hello_world
      docker_image:
        name: pparth27743/hello_world
        source: pull
    - name: Create default containers
      docker_container:
        name: c1
        image: pparth27743/hello_world
        state: present


